import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { COLORS, globalStyles } from "./pdf-styles";
import type { ReactNode } from "react";

const localStyles = StyleSheet.create({
  coverPage: {
    ...globalStyles.page,
    justifyContent: "center",
    alignItems: "center",
  },
  coverTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  coverSubtitle: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginBottom: 24,
    textAlign: "center",
  },
  coverMeta: {
    fontSize: 10,
    color: COLORS.textMuted,
    marginBottom: 6,
    textAlign: "center",
  },
  coverBox: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 24,
    marginTop: 16,
    minWidth: 300,
    alignItems: "center",
  },
  coverUrl: {
    fontSize: 11,
    color: COLORS.textPrimary,
    marginBottom: 4,
    textAlign: "center",
    maxWidth: 400,
  },
});

interface PdfDocumentProps {
  scan: {
    id: string;
    url: string;
    status: string;
    scanType: string;
    createdAt: string;
    project?: {
      name: string;
    } | null;
  };
  reportTitle: string;
  children: ReactNode;
}

function CoverPage({
  scan,
  reportTitle,
}: {
  scan: PdfDocumentProps["scan"];
  reportTitle: string;
}) {
  const date = new Date(scan.createdAt).toLocaleString();
  return (
    <Page style={localStyles.coverPage}>
      <Text style={localStyles.coverTitle}>{reportTitle}</Text>
      <Text style={localStyles.coverSubtitle}>Inspectron Scan Report</Text>
      <View style={localStyles.coverBox}>
        <Text style={localStyles.coverUrl}>{scan.url}</Text>
        {scan.project && (
          <Text style={localStyles.coverMeta}>
            Project: {scan.project.name}
          </Text>
        )}
        <Text style={localStyles.coverMeta}>Scan ID: {scan.id}</Text>
        <Text style={localStyles.coverMeta}>Type: {scan.scanType}</Text>
        <Text style={localStyles.coverMeta}>Status: {scan.status}</Text>
        <Text style={localStyles.coverMeta}>Date: {date}</Text>
      </View>
    </Page>
  );
}

function Header({ scan }: { scan: PdfDocumentProps["scan"] }) {
  return (
    <View style={globalStyles.header} fixed>
      <View>
        <Text style={globalStyles.headerTitle}>Inspectron</Text>
      </View>
      <View style={{ alignItems: "flex-end" }}>
        <Text style={globalStyles.headerMeta}>{scan.url}</Text>
        <Text style={globalStyles.headerMeta}>{scan.scanType} Scan</Text>
      </View>
    </View>
  );
}

function Footer({ scan }: { scan: PdfDocumentProps["scan"] }) {
  return (
    <View style={globalStyles.footer} fixed>
      <Text style={globalStyles.footerText}>
        Generated by Inspectron · Scan #{scan.id}
      </Text>
      <Text
        style={globalStyles.footerText}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

export function PdfDocument({ scan, reportTitle, children }: PdfDocumentProps) {
  return (
    <Document>
      <CoverPage scan={scan} reportTitle={reportTitle} />
      <Page style={globalStyles.page}>
        <Header scan={scan} />
        {children}
        <Footer scan={scan} />
      </Page>
    </Document>
  );
}
